# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: grading_app
      MYSQL_USER: gb_grading
      MYSQL_PASSWORD: 'gb_grading'
      MYSQL_ROOT_PASSWORD: 'NO'
    networks:
      - george-bugwak

  grading:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=gb_grading
      - DB_PASSWORD=gb_grading
      - DB_DATABASE=grading_app
    volumes:
      - './project:/app'
    depends_on:
      - db
    networks:
      - george-bugwak
      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    networks:
      - george-bugwak
      
networks:
  george-bugwak:
    driver: bridge